### ISSUE TITLE
Drupal 9 upgrade issue

### ISSUE THREAD

**Issue by ht1ppens** [jtyocum/drupal8-uwauth#12]
When I cleared my cache (_drush cr_) after running the composer update to go from drupal 8 to drupal 9 I got the following error message: 
 The service "uwauth.eventsubscriber" has a dependency on a non-existent service "entity.manager".

I updated line 18 in the uwauth.services.yml file to
      - '@entity_type.manager'

And that fixed it.

**Comment by ht1ppens** [comment]
Looks like this is a duplicate of a previous issue -

**Comment by fgm** [comment]
That was https://github.com/deohs/uwauth/issues/10 . The question is how did you get that error since this was fixed when that issue was merged in 07/2021. Maybe you're using version 3.0.0 ? If that's the case, you should be using the dev version instead, as that fix is not in any current release. Ping @tkiehne : maybe you could create a 3.0.1 release, since that's a pretty major bug, even though the fix is trivial.

**Comment by tkiehne** [comment]
Apologies everyone - I had been waiting for an opportunity to test on D9 but that hadn't materialized before I lost focus.  I just published a 3.0.1 release.
